# Generated by Django 4.2.3 on 2023-07-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
