# Generated by Django 4.2.3 on 2023-08-01 05:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("room_api", "0003_alter_room_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nane", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField(max_length=10)),
                ("message", models.TextField()),
            ],
        ),
    ]
