# Generated by Django 4.2.3 on 2023-08-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_api", "0006_alter_contactus_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_drainage_available",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="is_drinking_water",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="is_electriciy_charge",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="is_water_supply",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
