# Generated by Django 5.0 on 2024-01-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_api', '0009_room_booked_by_room_image_url_room_is_assigned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image_url',
        ),
        migrations.AddField(
            model_name='room',
            name='image_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
