# Generated by Django 5.0 on 2024-01-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_api', '0010_remove_room_image_remove_room_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image_data',
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
    ]
